export const GET_ALL_DECKS = "GET_ALL_DECKS"
export const ADD_DECK = "ADD_DECK"
export const ADD_QUESTION = "ADD_QUESTION"
export const IS_LOADING = "IS_LOADING"
export const STOP_LOADING = "STOP_LOADING"
